app:
  name: tixgo
  environment: dev
  debug_mode: true

server:
  host: localhost
  port: 8000
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 10s

database: 
  type: postgres
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: tixgo
  ssl_mode: disable
  max_open_conns: 10
  max_idle_conns: 5
  max_lifetime: 3600s
  max_idle_time: 3600s
  migration_path: file:///Users/admin/Developer/tixgo/migrations

jwt:
  secret_key: "secret"
  access_token_expiry: 900s
  refresh_token_expiry: 604800s

kafka:
  brokers:
    - localhost:9092